package GUI;

/**
 *
 * @author Lenovo
 */
public class Menu extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 private PhanCongCongViec panelphancong;
    private ThongTinCaNhan panelxemtt;
    private QuanLiDuAn panelquanliduan;
    private QuanLyNhanVien panelquanlinv;
   private QuanLyCongViec panelcv;
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_xemthongtin = new javax.swing.JMenuItem();
        jMenuItem_dangxuat = new javax.swing.JMenuItem();
        jMenuItem_thoat = new javax.swing.JMenuItem();
        jMenu_nhanvien = new javax.swing.JMenu();
        jMenuItem_quanlinhanvien = new javax.swing.JMenuItem();
        jMenu_duan = new javax.swing.JMenu();
        jMenuItem_quanliduan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_qlcongviec = new javax.swing.JMenuItem();
        jMenuItem_phancongcv = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Hệ thống");


        jMenuItem_xemthongtin.setText("Xem thông tin cá nhân");

        jMenuItem_xemthongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_xemthongtinActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_xemthongtin);

        jMenuItem_dangxuat.setText("Đăng xuất");
        jMenuItem_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_dangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_dangxuat);


        jMenuItem_thoat.setText("Thoát");

        jMenuItem_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_thoatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_thoat);

        jMenuBar1.add(jMenu1);


        jMenu_nhanvien.setText("Nhân viên");

        jMenu_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_nhanvienActionPerformed(evt);
            }
        });


        jMenuItem_quanlinhanvien.setText("Quản lí nhân viên");

        jMenuItem_quanlinhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_quanlinhanvienActionPerformed(evt);
            }
        });
        jMenu_nhanvien.add(jMenuItem_quanlinhanvien);

        jMenuBar1.add(jMenu_nhanvien);


        jMenu_duan.setText("Dự án");

        jMenu_duan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_duanActionPerformed(evt);
            }
        });


        jMenuItem_quanliduan.setText("Quản lí dự án");
//Bỏ cmt ở đây
        jMenuItem_quanliduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_quanliduanActionPerformed(evt);
            }
        });
        jMenu_duan.add(jMenuItem_quanliduan);

        jMenuBar1.add(jMenu_duan);


        jMenu4.setText("Công việc");

        jMenuItem_qlcongviec.setText("Quản lí công việc");
      //Bỏ cmt ở đây
        jMenuItem_qlcongviec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_qlcongviecActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_qlcongviec);


        jMenuItem_phancongcv.setText("Phân công công việc");
      //Bỏ cmt ở đây
        jMenuItem_phancongcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_phancongcvActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_phancongcv);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_xemthongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_xemthongtinActionPerformed
       if (panelxemtt == null) {
			panelxemtt = new ThongTinCaNhan();

			jTabbedPane1.addTab("Xem thông tin", panelxemtt);

		}
        jTabbedPane1.setSelectedComponent(panelxemtt);


    }//GEN-LAST:event_jMenuItem_xemthongtinActionPerformed

    private void jMenuItem_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_dangxuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_dangxuatActionPerformed

    private void jMenuItem_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_thoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_thoatActionPerformed

    private void jMenu_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_nhanvienActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu_nhanvienActionPerformed

    private void jMenu_duanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_duanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu_duanActionPerformed
  //Bỏ cmt ở đây
    private void jMenuItem_qlcongviecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_qlcongviecActionPerformed
        // TODO add your handling code here:
        if(panelcv == null)
        {
            panelcv = new QuanLyCongViec();

            jTabbedPane1.addTab("Quản lí công việc", panelcv);

        }
        jTabbedPane1.setSelectedComponent(panelcv);
    }//GEN-LAST:event_jMenuItem_qlcongviecActionPerformed
  //Bỏ cmt ở đây
    private void jMenuItem_phancongcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_phancongcvActionPerformed
        if(panelphancong == null)
        {
        	panelphancong = new PhanCongCongViec();

        	jTabbedPane1.addTab("Phân công công việc", panelphancong);

        }
        jTabbedPane1.setSelectedComponent(panelphancong);
    }//GEN-LAST:event_jMenuItem_phancongcvActionPerformed

    private void jMenuItem_quanlinhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_quanlinhanvienActionPerformed
        // TODO add your handling code here:
         if(panelquanlinv == null)
        {
            panelquanlinv = new QuanLyNhanVien();

            jTabbedPane1.addTab("Quản lí nhân viên", panelquanlinv);

        }
        jTabbedPane1.setSelectedComponent(panelquanlinv);
    }//GEN-LAST:event_jMenuItem_quanlinhanvienActionPerformed
  //Bỏ cmt ở đây
    private void jMenuItem_quanliduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_quanliduanActionPerformed
        // TODO add your handling code here:
        if(panelquanliduan == null)
        {
            panelquanliduan = new QuanLiDuAn();

            jTabbedPane1.addTab("Quản lí dự án", panelquanliduan);

        }
        jTabbedPane1.setSelectedComponent(panelquanliduan);
    }//GEN-LAST:event_jMenuItem_quanliduanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_dangxuat;
    private javax.swing.JMenuItem jMenuItem_phancongcv;
    private javax.swing.JMenuItem jMenuItem_qlcongviec;
    private javax.swing.JMenuItem jMenuItem_quanliduan;
    private javax.swing.JMenuItem jMenuItem_quanlinhanvien;
    private javax.swing.JMenuItem jMenuItem_thoat;
    private javax.swing.JMenuItem jMenuItem_xemthongtin;
    private javax.swing.JMenu jMenu_duan;
    private javax.swing.JMenu jMenu_nhanvien;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
